### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by AikoTR** [ShadowLp174/discord-stt#1]
Transcriber-error:  TypeError: Cannot read properties of undefined (reading 'replace')
    at Transcriber.transcribe (C:\Users\aikof\Documents\Dev\DiscordBotTestVoice\node_modules\discord-speech-to-text\transcriber.js:59:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Decoder.<anonymous> (C:\Users\aikof\Documents\Dev\DiscordBotTestVoice\node_modules\discord-speech-to-text\transcriber.js:88:28)

**Comment by ShadowLp174** [comment]
Hhhm...

I'll have a look at that soon:tm:

May I ask what exactly you did - This would make things a lot easier :) (code would be very useful)

**Comment by EBMOfficial** [comment]
I'm having this issue too. The code that AikoTR is very likely referring to is the code for the parse function. 

`function parse(string, possible) {
    let output = string.repeat(1);
    string = string.replace("/\./g", "");
    string = string.toLowerCase().replace("computer", "").trim();
    if (string.includes(" ")) string = string.split(" ")[0];
    string = string.trim();
    if (!possible.includes(string)) return false;
    output = output.replace(/\./g, "").toLowerCase().replace("computer", "").trim();
    return output;
  }

// Usage:
let command = parse(TranscribedText, ["play", "pause", "resume", "skip", "shuffle", "list"]);`

**Comment by ShadowLp174** [comment]
Hhm

Sometimes there is an error with wit or similar, I can't change... In this cases, the `transcript.text` property will be undefined... That could be the problem here but I'm not sure.

I'll look into it tomorrow but if you want to try fixing it, add the following line before the parse function: 

```
if (!TranscribedText) return;
```

**Comment by ShadowLp174** [comment]
Hhm

Sometimes there is an error with wit or similar, I can't change... In this cases, the `transcript.text` property will be undefined... That could be the problem here but I'm not sure.

I'll look into it tomorrow but if you want to try fixing it, add the following line before the parse function: 

```
if (!TranscribedText) return;
```

If there is a Transcriber error before the problem in the logs, please tell me!
